### PR TITLE
Renamed from natlinkpy to natlink in python packaging index.

### PR DESCRIPTION
**Pull request by dougransom**

### CODE REVIEW

**Comment by LexiconCode** [comment]
After configuring the UserDirectory on 1st start of Dragon this is the output. It seems natlinkmain is being initialized twice?
```
UnimacroDirectory not found in Git area or in "lib/site-packages/unimacro", return ""
VocolaDirectory not found in Git area or in "lib/site-packages/vocola2", return ""
UnimacroDirectory not found in Git area or in "lib/site-packages/unimacro", return ""
VocolaDirectory not found in Git area or in "lib/site-packages/vocola2", return ""
Instructions for attaching a python debugger are in C:\Users\Main\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\natlinkpy\MacroSystem\core\debugging python instructions.docx 
--
-- natlinkmain starting...
Vocola is disabled
Unimacro is disabled
include UserDirectory: "D:\Backup\Library\Documents\Caster" in grammars to load
include baseDirectory "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\natlinkpy\MacroSystem" in grammars to load
--- natlinkstartup starting...
Caster User Directory: C:\Users\Main\AppData\Local\caster
DPI awareness could not be set; it has been set already.
markdown module name is already in use: C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\markdown\__init__.py
The rule GrammarActivatorRule was set to active.
The rule HooksActivationRule was set to active.
Skipping rule TobiiRule because it is enabled but not loaded.

*- Starting Caster v 1.6.16 -*
natlinkmain started from C:\Users\Main\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\natlinkpy\MacroSystem\core:
  Natlink version: 4.2
  DNS version: 15
  Python version: 38
  Windows Version: 10
User defined macro's enabled, UserDirectory:
  D:\Backup\Library\Documents\Caster
----------------------------------------
UnimacroDirectory not found in Git area or in "lib/site-packages/unimacro", return ""
VocolaDirectory not found in Git area or in "lib/site-packages/vocola2", return ""
--
-- natlinkmain starting...
natlinkmain started from C:\Users\Main\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\natlinkpy\MacroSystem\core:
  Natlink version: 4.2
  DNS version: 15
  Python version: 38
  Windows Version: 10
User defined macro's enabled, UserDirectory:
  D:\Backup\Library\Documents\Caster
----------------------------------------
```

**Comment by dougransom** [comment]
I don't think it is starting twice.  here is my output.

```
natlinkstatus, addToPath: C:\Python38-32\Lib\site-packages\unimacro
natlinkstatus, addToPath: C:\Python38-32\Lib\site-packages\vocola2
Instructions for attaching a python debugger are in C:\Python38-32\Lib\site-packages\natlinkpy\MacroSystem\core\debugging python instructions.docx 
--
-- natlinkmain starting...
include Vocola in grammars to load
include Unimacro in grammars to load
no UserDirectory specified
include baseDirectory "C:\Python38-32\Lib\site-packages\natlinkpy\MacroSystem" in grammars to load
from setSearchImportDirs add to path: C:\Users\dougr\OneDrive\doug\dication_toolbox\p3voice\unimacro\ActiveGrammars
from setSearchImportDirs add to path: C:\Users\dougr\OneDrive\doug\dication_toolbox\p3voice\vocola\CompiledGrammars
from setSearchImportDirs add to path: C:\Python38-32\lib\site-packages\vocola2
**--- natlinkstartup starting...**
VocolaEnabled: True
thisDir of _vocola_main: C:\Python38-32\lib\site-packages\vocola2 not equal to VocolaDirectory from natlinkstatus: C:\Python38-32\lib\site-packages\vocola2
_vocola_main, Vocola is Enabled, check sys.path for ExecFolder and ExtensionsFolder
_vocola_main, add to sys.path: C:\Python38-32\lib\site-packages\vocola2\exec
_vocola_main, add to sys.path: C:\Python38-32\lib\site-packages\vocola2\extensions
Vocola version 2.8.6 starting...
_vocola_main calls vcl2py.py, grammars go to folder: C:\Users\dougr\OneDrive\doug\dication_toolbox\p3voice\vocola\CompiledGrammars
initializing/loading DictGrammar!!
messageDictGrammar initialized
registering grammar object: control: <inigr: control>
failed to load gramSpec of IniGrammar <inigr: control>
registering grammar object: clickbyvoice: <inigr: clickbyvoice>
failed to load gramSpec of IniGrammar <inigr: clickbyvoice>
Python path ['C:\\Python38-32\\lib\\site-packages\\vocola2', 'C:\\Users\\dougr\\OneDrive\\doug\\dication_toolbox\\p3voice\\vocola\\CompiledGrammars', 'C:\\Users\\dougr\\OneDrive\\doug\\dication_toolbox\\p3voice\\unimacro\\ActiveGrammars', 'C:\\Python38-32\\lib\\site-packages\\unimacro', 'C:\\Python38-32\\Lib\\site-packages\\natlinkpy\\MacroSystem', 'C:\\Program Files (x86)\\Nuance\\NaturallySpeaking15\\Program\\%PYTHONPATH%', 'C:\\Users\\dougr\\Doug Ransom Financial Services\\operations - Documents\\scripts\\bulk mutual funds', 'C:\\Python38-32\\python38.zip', 'C:\\Python38-32\\Lib\\site-packages\\natlinkpy\\MacroSystem\\core', 'C:\\Python38-32\\Lib', 'C:\\Python38-32\\DLLs', 'C:\\Program Files (x86)\\Nuance\\NaturallySpeaking15\\Program', 'C:\\Python38-32', 'C:\\Python38-32\\lib\\site-packages', 'C:\\Python38-32\\lib\\site-packages\\win32', 'C:\\Python38-32\\lib\\site-packages\\win32\\lib', 'C:\\Python38-32\\lib\\site-packages\\Pythonwin', 'C:\\Python38-32\\Lib\\site-packages\\natlinkpy\\MacroSystem\\core', 'C:\\Python38-32\\Lib\\site-packages\\unimacro', 'C:\\Python38-32\\Lib\\site-packages\\vocola2', 'C:\\Python38-32\\lib\\site-packages\\vocola2\\exec', 'C:\\Python38-32\\lib\\site-packages\\vocola2\\extensions', 'C:\\DT\\Natlink\\MacroSystem\\core']
debug_grammar initialize
debug initialize, by loading self.gramSpec
registering grammar object: debug natlink: <inigr: debug natlink>
failed to load gramSpec of IniGrammar <inigr: debug natlink>
IniGrammar switched on: debug natlink
_folders, drives ['lr', 'md', 'od', 'pf']
_folders, notify threshold milliseconds: 10
registering grammar object: folders: <inigr: folders>
failed to load gramSpec of IniGrammar <inigr: folders>
folders: warning, empty section for list "files" in inifile
folders: warning, empty section for list "websiteopenprograms" in inifile
no recentfolders in iniChangingData.ini
folders: warning, empty section for list "recentfolders" in inifile
no recentfolders in iniChangingData.ini
IniGrammar switched on: folders
registering grammar object: lines: <docstringgr: lines>
failed to load gramSpec of IniGrammar <docstringgr: lines>
lines: warning, empty section for list "afterwordaction" in inifile
IniGrammar switched on: lines
registering grammar object: tasks: <docstringgr: tasks>
failed to load gramSpec of IniGrammar <docstringgr: tasks>
tasks: warning, empty section for list "documentaction" in inifile
tasks: warning, empty section for list "monitors" in inifile
IniGrammar switched on: tasks
tasks: warning, empty section for list "documentaction" in inifile
tasks: warning, empty section for list "monitors" in inifile
IniGrammar switched on: tasks
IniGrammar tasks, all lists initialized...
registering grammar object: natspeak dialog: <inigr: natspeak dialog>
failed to load gramSpec of IniGrammar <inigr: natspeak dialog>
loaded: ['<chooserfd> exported = choose {number};\n<okcancelrfd> exported = (okay|OK) | Cancel;']
natlinkmain started from C:\Python38-32\Lib\site-packages\natlinkpy\MacroSystem\core:
  Natlink version: 4.2
  DNS version: 15
  Python version: 38
  Windows Version: 10
Unimacro enabled, UnimacroUserDirectory:
  C:\Users\dougr\OneDrive\doug\dication_toolbox\p3voice\unimacro
Vocola enabled, VocolaUserDirectory:
  C:\Users\dougr\OneDrive\doug\dication_toolbox\p3voice\vocola
----------------------------------------
--
UNregistering grammar object: control: <inigr: control>
UNregistering grammar object: clickbyvoice: <inigr: clickbyvoice>
function unload in _folders.py
unloading folders grammar
UNregistering grammar object: folders: <inigr: folders>
unloaded folders grammar
UNregistering grammar object: lines: <docstringgr: lines>
UNregistering grammar object: tasks: <docstringgr: tasks>
UNregistering grammar object: natspeak dialog: <inigr: natspeak dialog>
-- natlinkmain starting...
natlinkmain started from C:\Python38-32\Lib\site-packages\natlinkpy\MacroSystem\core:
  Natlink version: 4.2
  DNS version: 15
  Python version: 38
  Windows Version: 10
Unimacro enabled, UnimacroUserDirectory:
  C:\Users\dougr\OneDrive\doug\dication_toolbox\p3voice\unimacro
Vocola enabled, VocolaUserDirectory:
  C:\Users\dougr\OneDrive\doug\dication_toolbox\p3voice\vocola
----------------------------------------
VocolaEnabled: True
thisDir of _vocola_main: C:\Python38-32\lib\site-packages\vocola2 not equal to VocolaDirectory from natlinkstatus: C:\Python38-32\lib\site-packages\vocola2
_vocola_main, Vocola is Enabled, check sys.path for ExecFolder and ExtensionsFolder
Vocola version 2.8.6 starting...
_vocola_main calls vcl2py.py, grammars go to folder: C:\Users\dougr\OneDrive\doug\dication_toolbox\p3voice\vocola\CompiledGrammars
natlinkmain: 1 Vocola Compiled grammars to load
natlinkmain: 9 grammars to load
initializing/loading DictGrammar!!
messageDictGrammar initialized
registering grammar object: control: <inigr: control>
failed to load gramSpec of IniGrammar <inigr: control>
registering grammar object: clickbyvoice: <inigr: clickbyvoice>
failed to load gramSpec of IniGrammar <inigr: clickbyvoice>
Python path ['C:\\Python38-32\\lib\\site-packages\\vocola2', 'C:\\Users\\dougr\\OneDrive\\doug\\dication_toolbox\\p3voice\\vocola\\CompiledGrammars', 'C:\\Users\\dougr\\OneDrive\\doug\\dication_toolbox\\p3voice\\unimacro\\ActiveGrammars', 'C:\\Python38-32\\lib\\site-packages\\unimacro', 'C:\\Python38-32\\Lib\\site-packages\\natlinkpy\\MacroSystem', 'C:\\Program Files (x86)\\Nuance\\NaturallySpeaking15\\Program\\%PYTHONPATH%', 'C:\\Users\\dougr\\Doug Ransom Financial Services\\operations - Documents\\scripts\\bulk mutual funds', 'C:\\Python38-32\\python38.zip', 'C:\\Python38-32\\Lib\\site-packages\\natlinkpy\\MacroSystem\\core', 'C:\\Python38-32\\Lib', 'C:\\Python38-32\\DLLs', 'C:\\Program Files (x86)\\Nuance\\NaturallySpeaking15\\Program', 'C:\\Python38-32', 'C:\\Python38-32\\lib\\site-packages', 'C:\\Python38-32\\lib\\site-packages\\win32', 'C:\\Python38-32\\lib\\site-packages\\win32\\lib', 'C:\\Python38-32\\lib\\site-packages\\Pythonwin', 'C:\\Python38-32\\Lib\\site-packages\\natlinkpy\\MacroSystem\\core', 'C:\\Python38-32\\Lib\\site-packages\\unimacro', 'C:\\Python38-32\\Lib\\site-packages\\vocola2', 'C:\\Python38-32\\lib\\site-packages\\vocola2\\exec', 'C:\\Python38-32\\lib\\site-packages\\vocola2\\extensions', 'C:\\DT\\Natlink\\MacroSystem\\core']
debug_grammar initialize
debug initialize, by loading self.gramSpec
registering grammar object: debug natlink: <inigr: debug natlink>

```

**Comment by dougransom** [comment]
my output looks similar to yours, maybe main is starting twice?  

Is it going to break anything?

**Comment by LexiconCode** [comment]
> 
> 
> my output looks similar to yours, maybe main is starting twice?
> 
> Is it going to break anything?

I'm not sure it's too early to tell but it is something we should hammer out before beta release. Perhaps I can take a closer look this weekend.

**Comment by quintijn** [comment]
LexiconCode, it can happen that some functions perform twice or even a bit more. I cut out already a few recently. Tidying up things must be done at some moment, I agree. It does not harm the functioning of Natlink, I believe.

**Pull request merged**
