### PR TITLE
Python3 rewrite (ongoing)

### PR DESCRIPTION
**Pull request by kb100**

### CODE REVIEW

**Comment by quintijn** [comment]
James, Jan, I will delve into this ASAP, Quintijn

**Comment by quintijn** [comment]
Sorry, did not manage to merge things. Too many complications. James, I would like to discuss this with you...

**Comment by LexiconCode** [comment]
> 
> 
> Sorry, did not manage to merge things. Too many complications. James, I would like to discuss this with you...

What was the conclusion to this conversation?

**Comment by dougransom** [comment]
Guys, i think we should get this pull request dealt with?  I think it would be best for everyone to get synced up.   @kb100   it looked like @quintijn had trouble merging?  Maybe you could merge the dictation_toolbox/master into your fork and do the merges and we can ask @quintijn to perform the pull request?

**Comment by LexiconCode** [comment]
if there's no intent to merge @quintijn this should be closeed.

**Comment by dougransom** [comment]
@LexiconCode @kb100 Lets close it.  A lot has changed since @kb100 forked it, if they come back to the project we can revisit.

**Comment by LexiconCode** [comment]
All right I'll close and it can be reopened if needed.

**Pull request closed without merging**
